apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gitlab-nas-sc
mountOptions:
  - 'nolock,tcp,noresvport'
  - vers=3
parameters:
  server: '<nas-mount-point>.cn-hangzhou.nas.aliyuncs.com:/'
  volumeAs: subpath
provisioner: nasplugin.csi.alibabacloud.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
