apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pgsql-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gitlab-nas-sc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-pgsql-cm
  namespace: gitlab
data:
  POSTGRESQL_POSTGRES_PASSWORD: 'password'
  POSTGRESQL_USERNAME: gitlab
  POSTGRESQL_PASSWORD: 'password'
  POSTGRESQL_DATABASE: gitlabhq_production
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: gitlab-pgsql
  name: gitlab-pgsql
  namespace: gitlab
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gitlab-pgsql
  serviceName: gitlab-pgsql-svc
  template:
    metadata:
      labels:
        app: gitlab-pgsql
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: gitlab-pgsql-cm
          image: 'bitnami/postgresql:14.8.0'
          imagePullPolicy: IfNotPresent
          name: gitlab-pgsql
          ports:
            - containerPort: 5432
              name: pgsql
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          securityContext:
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: pgsql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      terminationGracePeriodSeconds: 30
      volumes:
        - name: pgsql-data
          persistentVolumeClaim:
            claimName: gitlab-pgsql-pvc
  updateStrategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-pgsql-svc
  namespace: gitlab
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: gitlab-pgsql
